weights: yolov5m.pt
cfg: ./models/custom_yolov5m.yaml
data: ../data.yaml
hyp: data/hyp.scratch.yaml
epochs: 100
batch_size: 32
img_size:
- 1024
- 1024
rect: false
resume: false
nosave: false
notest: false
noautoanchor: false
evolve: false
bucket: ''
cache_images: true
image_weights: false
device: ''
multi_scale: false
single_cls: false
adam: false
sync_bn: false
workers: 8
project: runs/train
entity: null
name: custom_yolov5m_results
exist_ok: false
quad: false
linear_lr: false
label_smoothing: 0.0
upload_dataset: false
bbox_interval: -1
save_period: -1
artifact_alias: latest
local_rank: -1
save_dir: runs/train/custom_yolov5m_results
