weights: yolov5m.pt
cfg: ./models/custom_yolov5m.yaml
data: ../data.yaml
hyp: data/hyps/hyp.scratch.yaml
epochs: 100
batch_size: 12
img_size:
- 800
- 800
rect: false
resume: false
nosave: false
notest: false
noautoanchor: false
evolve: null
bucket: ''
cache_images: false
image_weights: false
device: ''
multi_scale: false
single_cls: false
adam: false
sync_bn: false
workers: 8
project: runs/train
entity: null
name: yolov5m_results
exist_ok: false
quad: false
linear_lr: false
label_smoothing: 0.0
upload_dataset: false
bbox_interval: -1
save_period: -1
artifact_alias: latest
local_rank: -1
save_dir: runs/train/yolov5m_results2
